apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q7m8n4d0d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q7m8n4d0d-go 
  name: q7m8n4d0d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q7m8n4d0d-go 
