apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q7m8n4d0d-go 
  janus-idp.io/tekton: q7m8n4d0d-go
  backstage.io/kubernetes-id: q7m8n4d0d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q7m8n4d0d-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml